// <auto-generated />
namespace MadShoppers.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class mainclass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mainclass));
        
        string IMigrationMetadata.Id
        {
            get { return "201711221148566_mainclass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
