// <auto-generated />
namespace MadShoppers.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class enable_users : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(enable_users));
        
        string IMigrationMetadata.Id
        {
            get { return "201711290506440_enable_users"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
